version: "3"
services:
  backend:
    container_name: backend
    build: .
    image: backend
    environment:
      - MYSQL_DATABASE=ProductCase
      - MYSQL_USER=test221
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - /home/int222/backend:/application/images/products, /home/int222/backend:/application/images/profiles
    networks:
       int222:
          ipv4_address: 172.10.0.3

networks:
  default:
    external:
       name: int222
  int222:
    external: true